spring.application.name=links-manager-back-springboot

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/links-manager-database-postgres
spring.datasource.username=admin
spring.datasource.password=admin

jwt-token-issuer=JWT_TOKEN_ISSUER
jwt-token-secret=JWT_TOKEN_SECRET
